config/routes.rb
Rails.application.routes.draw do
  root   'top_page#home'
  get   '/signup',   to: 'users#new'
  post  '/signup',   to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resource   :users,  only: [:edit, :update, :destroy]
  resources  :users,  only: [:show, :index]
  resources  :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  belongs_to :user, foreign_key: 'group_creator_id'
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :groups, foreign_key: 'group_creator_id'
  attr_accessor :remember_token
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :activity_area, length: { maximum: 30 }
  validates :like_weapon, length: { maximum: 50 }
  
  class << self
    def digest(token)
      BCrypt::Password.create(token, cost: BCrypt::Engine.cost)
    end
  
    #ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  #永続的にユーザーをDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #トークンとダイジェストが一致するか確認
  def authenticated?(token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(token)
  end
  
  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :logged_in_user
  add_flash_types  :success, :info, :warning, :danger
  helper_method :current_user, :logged_in?, :current_user?
  
#ログイン関連
  #ログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  #永続的にログインする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  #永続的なログインを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # #現在のユーザー(永続的か一時的なログインか確認し返す)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  #ログインしているか確認
  def logged_in?
    current_user.present?
  end
  
  #ログアウト
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  #ログイン済みのユーザーか確認する
  def current_user?(user)
    user == current_user
  end
  
  #ログインしているか確認し、していなければログイン画面を返す
  def logged_in_user
    unless logged_in?
      redirect_to login_url, danger: "ログインしてください"
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :group_join, only: [:show]
  
  def show
     @group = Group.find(params[:id])
  end
  
  def index
    @groups = Group.all
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      @group.users << current_user
      redirect_to @group, success: "グループを作成しました"
    else
      render "new"
    end
  end
  
  def edit
    @group = current_user.groups.find(params[:id]) 
  end
  
  def update
    @group = current_user.groups.find(params[:id]) 
    if @group.update(group_params)
      redirect_to group_path, success: "プロフィールを更新しました"
    else
      render 'edit'
    end
  end
  
  private
  
  def group_params
    params.require(:group).permit(:name, :description)
  end
  
  def group_join
    @group = Group.find(params[:id])
    unless @group.users.exists?(current_user.id)
      @group.users << current_user
      flash.now[:success] = "グループに参加しました"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user
  
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'ユーザー名とパスワードの組み合わせが正しくありません'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  skip_before_action :logged_in_user
  
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in_user, only: [:show, :new, :create]
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.page(params[:page]).per(20)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, success: "登録が完了しました！楽しんでくださいね！"
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user, success: "プロフィールを更新しました"
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation,
                                  :activity_area, :like_weapon, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.erb
<% provide(:title, "グループ編集") %>
<h1>グループ編集画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/group_form' %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'グループ一覧') %>
<h1>グループ一覧</h1>
<ul class="groups">
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
    <% if  group.users.exists?(current_user.id) %>
      <li><%= link_to "編集", edit_group_path(group) %></li>
    <% end %>
  <% end %>
</ul>

app/views/groups/new.html.erb
<% provide(:title, "グループ作成") %>
<h1>グループ作成画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/group_form' %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="group_info">
      <h1><%= @group.name %></h1>
      <h1><%= @group.description %></h1>
    </section>
  </aside>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "サバゲーコミュ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",       root_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <li><%= link_to "グループ一覧", groups_path %></li>
        <li><%= link_to "検索",         "#" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "編集", edit_users_path(current_user) %></li>
              <li><%= link_to "グループ作成", new_group_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.present? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力に誤りがあります <%= pluralize(model.errors.count, "エラー") %>.
    </div>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%=msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_group.html.erb
<%= form_with model: @group, local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <%= f.label :グループ名 %>
  <%= f.text_field :name, class: 'form-control' %>
      
  <%= f.label :概要記入欄 %>
  <%= f.text_area :description,  class: 'form-control' %>
  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/shared/_group_form.html.erb
<%= form_with model: @group, local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <%= f.label :グループ名 %>
  <%= f.text_field :name, class: 'form-control' %>
      
  <%= f.label :概要記入欄 %>
  <%= f.text_area :description,  class: 'form-control' %>
  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user.html.erb
<%= form_with(model: user, url: url, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <%= f.label :ユーザー名 %>
  <%= f.text_field :name, class: 'form-control' %>
            
  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>
            
  <%= f.label :パスワード確認, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
          
  <%= f.label :活動地域 %>
  <%= f.text_field :activity_area, class: 'form-control' %>
            
  <%= f.label :好きな銃 %>
  <%= f.text_field :like_weapon, class: 'form-control' %>
      
<% if user.image? %>
  <%= image_tag user.image.url %>
<% end %> 
  <%= f.file_field :image %>
  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_form.html.erb
<%= form_with(model: user, url: url, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <%= f.label :ユーザー名 %>
  <%= f.text_field :name, class: 'form-control' %>
            
  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>
            
  <%= f.label :パスワード確認, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
          
  <%= f.label :活動地域 %>
  <%= f.text_field :activity_area, class: 'form-control' %>
            
  <%= f.label :好きな銃 %>
  <%= f.text_field :like_weapon, class: 'form-control' %>
      
<% if user.image? %>
  <%= image_tag user.image.url %>
<% end %> 
  <%= f.file_field :image %>
  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/top_page/home.html.erb
<div class="center jumbotron">
  <h1>サバゲーを一緒に楽しみましょう！</h1>
  <%= link_to image_tag("rails.png", alt: "Rails logo", width: 900, height: 400) %>
  <%= link_to "登録ページへ", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "編集") %>
<h1>プロフィール編集画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/user_form', user: current_user, url: users_path %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>
<ul class="users">
  <% @users.each do |user| %>
  <li>
    <% if user.image.present? %>
      <%= image_tag user.image_url, size: 50 %>
    <% end %>
    <%= link_to user.name, user %>
  </li>
  <% end %>
  <%= paginate @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, '登録ページ') %>
<h1>登録画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/user_form', user: @user, url: signup_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <% if @user.image? %>
        <%= image_tag @user.image.url %>
      <% end %> 
        <h1>ユーザー：<%= @user.name %></h1>
        <h1>活動地域：<%= @user.activity_area %></h1>
        <h1>好きな銃：<%= @user.like_weapon %></h1>
    </section>
  </aside>
</div>